### ISSUE TITLE
Implicit any breaks builds

### ISSUE THREAD

**Issue by eseliger** [ui-router/core#50] opened 2017-04-24 16:19 UTC
Since the new core is written completely in TypeScript, there would be no need for any external typings anymore, allowing the api changes to be in the type definitions at the time of release as well, but the problem is, that no `noImplicitAny` checks nor `strictNullChecks` are done by the typescript compiler atm. This breaks the build for everyone using this and making it impossible to use the integrated type definitions at the time.

**Comment by felixfbecker** [comment] 2017-04-24 17:05
This blocks our adoption of v1

**Comment by Kukkimonsuta** [comment] 2017-04-25 11:18
Workaround: set `skipLibCheck` in your `tsconfig` to ignore errors caused by library typings

**Comment by BrianMikinski** [comment] 2017-06-07 07:29
@Kukkimonsuta is it desirable for y'all enable strict null checking? If so I'd be interested in contributing. Would it merely be a case of adding the correct typings to the errors the compiler throws and insuring all tests pass or is there more to it?

**Comment by Kukkimonsuta** [comment] 2017-06-07 08:22
`strictNullChecks` have quite slow adoption from my experience, but I'd personally welcome it. To implement it correctly though, you need to have thorough knowledge of the code since you need to specify where `null` is valid and where not (compiler will help with things used internally, but public api may be more difficult to guess).

On the other hand `noImplicitAny` should be definitely enabled everywhere (at least in public api specified in typings).

**Comment by christopherthielen** [comment] 2017-07-11 03:30
5.0.6 should also be `strictNullChecks` compliant.

Closing because I think this is solved now, but reopen if necessary

**Closed by christopherthielen** 2017-07-11 03:30 UTC
