### ISSUE TITLE
_.extend implementation breaks in IE11 when string is passed in

### ISSUE THREAD

**Issue by alalonde** [ui-router/core#57] opened 2017-06-02 16:27 UTC
This manifests for me when running version 1.0.3 in an angular 1.x app, with e.g. states: 

```
var states = [{
    name: 'liheap',
    url: '/liheap',
    parent: 'app',
    template: '<ui-view></ui-view>',
    redirectTo: 'liheap.vendor'
  }, {
    name: 'liheap.vendor',
    url: '/vendors',
    template: '<ui-view></ui-view>',
    redirectTo: 'liheap.vendor.list'
  }, {
    name: 'liheap.vendor.list',
    ...
  }];
```

On the transition to 'liheap.vendor.list', it throws a
`Object.keys: argument is not an Object`

on line https://github.com/ui-router/core/blob/master/src/common/common.ts#L579 where the second argument is a string, which causes the transition to fail.  

I believe the root cause is discussed here: https://stackoverflow.com/questions/31917961/object-keys-behavior-in-chrome-and-ie-11

**Comment by christopherthielen** [comment] 2017-06-06 19:24
UI-Router shouldn't be calling `extend` with a string;  

can you show me how to reproduce this?

You can start here: 
http://plnkr.co/edit/CcxVK5hq4DmfUqoO4K1B?p=preview

**Comment by alalonde** [comment] 2017-06-07 21:36
Here is a demonstration:  http://plnkr.co/edit/Oybvbw1nrMFXy9yy2m1G?p=preview

The problem is in the onSuccess transition -- the use case is to detect when the state has been reloaded.  In IE it throws an error as soon as you leave that state though.

**Comment by christopherthielen** [comment] 2017-06-10 20:01
@alalonde thanks for the plunker.

The API for `onSuccess` does not take a string.  [It takes an object with `to`, `from`, `entering`, `exiting`, or `retained` properties.](https://ui-router.github.io/ng1/docs/latest/interfaces/transition.hookmatchcriteria.html)

I think you would want `$transitions.onSuccess({ exiting: $state.current.name, entering: $state.current.name } ...` to detect when the state is being reloaded.

Note you should always deregister hooks in $onDestroy that were registered by a component
Also note that the hook must use a higher priority, otherwise the $onDestroy is invoked before the hook can be fired.
http://plnkr.co/edit/IoTItAoF1ah3iTqd9hHA?p=preview

Note: if you use `uiCanExit` then you can avoid the manual deregistration:
http://plnkr.co/edit/PUMmoIGKyF1NEX8sFeWG?p=info



Im closing this because the reported issue (_extend and IE) is due to passing invalid arguments to the API

**Closed by christopherthielen** 2017-06-10 20:01 UTC

**Comment by alalonde** [comment] 2017-06-11 03:02
Thanks for the tips.  When I isolated the issue I ended up switching the hook to use the to/from format you mentioned.  The string used to work in `beta.3`, but no matter; seems to work now.
