### ISSUE TITLE
$state.is not respecting `options.relative`

### ISSUE THREAD

**Issue by simshanith** [ui-router/core#92] opened 2017-12-04 20:59 UTC
Problem: `stateService.is` always uses `stateService.$current` when comparing states.

Expected: When `options.relative` is passed a `StateOrName`, the comparison should be relative to the passed `StateOrName`.

https://github.com/ui-router/core/blob/master/src/state/stateService.ts#L413

Perhaps I am missing something; is there anyway to compare two states regardless of current state? E.g.

```js
// $state.current === { name: 'foo' };
$state.is($state.get('bar'), null, {
  relative: $state.get('bar'),
});
// Expected: true
// Actual: false
```

**Comment by christopherthielen** [comment] 2017-12-22 01:12
> stateService.is always uses stateService.$current when comparing states.

[`$state.is` checks if the current state is the provided state](https://ui-router.github.io/ng1/docs/latest/classes/state.stateservice.html#is)

This function is not used to compare two arbitrary states.  It's only used to test if the current state (and parameters) match the provided state.  Typically this is used for doing things like `ui-sref-active` (if the linked state is active, then do something special like highlight the link).

---

`options.relative` is used to look up a relative state.  For example, if you the current state is `foo.bar` then you could do `$state.is('.bar', null, { relative: 'foo' })`.

---

> is there anyway to compare two states regardless of current state? 

You can simply check for equality.  ```$state.get(state1) === $state.get(state2)``` 

Closing because `options.relative` is working as designed

**Closed by christopherthielen** 2017-12-22 01:12 UTC

**Comment by simshanith** [comment] 2017-12-22 18:53
Thanks @christopherthielen - the simple equality check is what I ended up doing.

It would be nice to have a utility to compare `StateOrNames` with the same kind of normalization, without having to check if a given object is a `StateDeclaration` or string / state name, though the strict equality check suffices when given two states.
