### ISSUE TITLE
Inject resolved value into onExit function

### ISSUE THREAD

**Issue by RaviDesai** [ui-router/core#87] opened 2017-11-02 16:36 UTC
This is a duplicate of one reported in angular-ui/ui-router: https://github.com/angular-ui/ui-router/issues/3081.  Which seems to have been resolved

I have a state like this:
```
.state('datasetroles', {
    url: '/dataset/roles',
    templateUrl: 'datasetroles.html',
    controller: DataSetRolesViewController,
    resolve: {
        vm: ['datasets', (datasets) => {
		return new DataSetRolesViewModel(datasets);
	}]
    },
    onExit: ['vm', function (vm) {
        vm.dispose();
    }]
}
```

when I exit this state I see the following exceptions in the console: 

```
stateService.js:43 Error: [$injector:unpr] Unknown provider: vmProvider <- vm
http://errors.angularjs.org/1.5.7/$injector/unpr?p0=vmProvider%20%3C-%20vm
    at angular.js:68
    at angular.js:4502
    at Object.getService [as get] (angular.js:4655)
    at angular.js:4507
    at getService (angular.js:4655)
    at injectionArgs (angular.js:4679)
    at Object.invoke (angular.js:4701)
    at decoratedNg1Hook (ui-router-angularjs.js:460)
    at onEnterExitRetain.js:15
    at invokeCallback (transitionHook.js:51)
```

Is there a way to get the resolved values (when I enter the state) to be injected into the onExit function?

**Comment by christopherthielen** [comment] 2017-12-22 01:03
For `@uirouter/angularjs`?  This should be the case today.  There is [even a test for it](https://github.com/angular-ui/ui-router/commit/c91b65a8a9c0f684d3d154601d52ce7e6cbc1619).

Here's a plunker which demonstrates that it should work: http://plnkr.co/edit/LFKUh4r3p6ZCDXEESizu?p=preview

Can you provide a plunker which shows how to reproduce the bug?

**Comment by christopherthielen** [comment] 2018-01-10 04:35
Here's a plunker which shows onExit working as expected

http://plnkr.co/edit/iSXxhplQC7s8gheYBibR?p=preview

Closing because I can't reproduce this.

**Closed by christopherthielen** 2018-01-10 04:35 UTC
