### ISSUE TITLE
resolve doesn't work correctly in the onEnter callback if both states have same resolve keys

### ISSUE THREAD

**Issue by Dzeks** [ui-router/core#95] opened 2017-12-19 13:52 UTC
Precondition:
There are 2 states, parent and parent.child, both states have the same resolvable parameter,
`resolve: {
   sameNameResolve: function() {return 'same name parent'}
}`
Parent state has onEnter callback, where this parameter is injected

Problem: 
When parent state onEnter callback is invoked for child state directly, we are navigating from the root page, 
the sameNameResolve will be undefined, if we remove this param as resolvable from child state, than in the parent onEnter callback this resolvable will work correctly

It was a valid scenario in the pre 1.x ui router
You can check the example in this plunker
https://plnkr.co/edit/2AgzGKSBIFRSVhJoDN7R?p=preview

Open plunker in the new tab, direct url and go to #!/about/details state,
check your console, you will see there undefined logged as second item from parents state onEnter callback
if you will navigate from root state to child state manually onEnter will work just fine and you will see
same name parent listed twice

**Comment by christopherthielen** [comment] 2017-12-22 01:17
Closing as a duplicate of https://github.com/angular-ui/ui-router/issues/3546

This will be fixed in the next release of `@uirouter/angularjs`

**Closed by christopherthielen** 2017-12-22 01:17 UTC
